### ISSUE TITLE
JS报错

### ISSUE THREAD

**Issue by phoenixg** [poach123/WechatFace#1]
![wechatface](https://cloud.githubusercontent.com/assets/990040/8123170/611f388a-10f7-11e5-8077-503f6844dd92.jpg)

另外顺便问下，看了源码里面的eval部分的加密js，请问这个解密后我看到很多x开头的内容，那是如何定义的？能不能给个思路？

**Comment by poach123** [comment]
没有X开头的啊，我传错代码了。已经上传了新的，老的也不是加密了，只是编码了，项目中不能出现。@phoenixg

**Comment by phoenixg** [comment]
谢谢啊，可是为什么会有 `h = f <= 0x2 ? _$[3] : _$[4];` 这样的代码啊，太晦涩了

**Comment by phoenixg** [comment]
依然有两个问题： 
1 `mail.css` -> `main.css`
2 `face.php` line 13, `$rth = curl_exec($curlobj);`, 打印出来是 `bad request`.
eg. `http://../WechatFace/face.php?url=http://images2.china.com/game/zh_cn/picnews/11128819/20130801/17976091_2013080109525911026600.jpg`

**Comment by phoenixg** [comment]
经过把 `face.php`第3行改成， `$img = $_GET['url'];` 现在curl出来内容了，但是年龄框没有出现在图片上面，JS报错：
![jsbaocuo](https://cloud.githubusercontent.com/assets/990040/8152241/48c6c174-134d-11e5-9e4e-d4357a2312d2.jpg)

**Comment by phoenixg** [comment]
添加了jquery 和  jquery ui 的库，
`
script src="http://libs.baidu.com/jquery/1.9.0/jquery.js"
`
`
script src="http://libs.baidu.com/jqueryui/1.8.22/jquery-ui.min.js "
`

代码也包裹在了：
`
$(document).ready(function(){});
`

现在报这个错误：
`TypeError: $(...).tooltip is not a function`

**Comment by phoenixg** [comment]
更换成了 bootstrap, 解决！
